### ISSUE TITLE
Uploaded media doesn't show up in media sidebar.

### ISSUE THREAD

**Issue by PurpleNinja225** [openbroadcaster/observer#10]
Installed as per prerequisites and used the ob.install.sh
using ffmpeg with symlinks from the dependency.txt
when uploading .avi videos, or any media for that matter I fill out the form (genres doesn't have any to select from btw) and hit save, I get a return message of it saving successfully and the media sidebar refreshes, however no new media pops up. I have drive using various media formats.

I checked the mysql db and it doesn't look like entries are being created in the media table. could be a disconnect between the frontend and the db?

**Comment by radiorob** [comment]
after you installed you checked config while logged in as Admin for errors
https://<IP_OF_SERVER/updates/

**Comment by PurpleNinja225** [comment]
![image](https://user-images.githubusercontent.com/5977403/79540602-e3fec200-8034-11ea-8d1e-d9f861b14db3.png)

**Comment by PurpleNinja225** [comment]
The ob-site is listed in the config.php as what it should be. I added a dns record to my domain registrar so the ob-site address is even viewable from outside the network. Not sure why it would still show up as not valid.

**Comment by maxlinux2000** [comment]
please add a record in the /etc/hosts of your linux distro

**Comment by PurpleNinja225** [comment]
Thanks for the tip! I was able to correct the etc/hosts file and that cleared up the issue with OB_SITE showing up red. I was also able fix my original issue of media not showing up after being uploaded. It was P E R M I S S I O N S ugh!  I feel really dumb i didn't check it more thoroughly. This issue can be closed.
