### ISSUE TITLE
How to schedule a show?

### ISSUE THREAD

**Issue by maxlinux2000** [openbroadcaster/observer#11]
Hi
I just installed in a local VM in order to try it an in the next future create a little web TV for my church.

The problem... after uploaded some medias (.ogg) I can't drag and drop in the calendar schedule page.
I'm using in the virtual  server ubuntu 18.04,  and in the client ubuntu 20.04 with firefox 77 and chrome 83.
Any ideas?

![Captura de pantalla de 2020-06-06 15-42-42](https://user-images.githubusercontent.com/5683921/83945650-6709f080-a80c-11ea-897d-31238731d581.png)

**Comment by radiorob** [comment]
Create a player first, Admin>Player Manager, then it will show up in the drop down for a schedule
