### ISSUE TITLE
fix any mysql errors so we can accept new PHP 8.1+ behavior

### ISSUE THREAD

**Issue by brookgagnon** [openbroadcaster/observer#163]
We missed some mysql error bugs (especially or maybe exclusively in updates) only caught now because PHP 8.1+ will fatal error on mysql error. We should fix these bugs.

Temporarily, we have set PHP 8.1+ to not fatal error in this case. But it's better if it does.

**Comment by Seehed** [comment]
So what is the solution to this?

**Comment by radiorob** [comment]
click schedule, save, doesn't do anything, should save and return to schedule, instead hangs,  click save the second time it gives this error, does it every time
![image2](https://github.com/openbroadcaster/observer/assets/4603894/1d2b21e8-16c3-4f88-b7e6-abbf385d892c)

**Comment by radiorob** [comment]
Fixed in [release v5.3.2](https://github.com/openbroadcaster/observer/releases/tag/v5.3.2)
