### ISSUE TITLE
Upload Media stuck on 'Processing Media...'

### ISSUE THREAD

**Issue by alphabitnz** [openbroadcaster/observer#17]
Hi, first time installing, OS is Linux Mint 20.2 and had to manually install as the script wasn't working.

Have worked through everything so far with config and dependencies looking good, but when I try to upload media I can't get past 'Processing Media...'

I've made sure all dependencies are installed (except for using mysql rather than mariadb, and I used the symlink commands documented for ffmpeg as libav-tools was depreciated) and believe I correctly set recursive ownership for user www-data on the media folder structure.
The file does appear in the /assets/uploads/ directory but without knowing how to check a log file I'm clueless as to what the roadblock is now.

![image](https://user-images.githubusercontent.com/9102111/134695752-7f4f304c-1278-40d3-bc95-fa4689313920.png)

**Comment by radiorob** [comment]
Thanks for reporting this.  First I would try uploading a small test file (PNG/SVG) to ensure everything works.  I've been seeing this issue with "processing Media" displays a long long time, after large size media file has been uploaded.  Some weird performance issues. Will pass along to @openbroadcaster/ob-core-devs.  After you installed everything, did you run updates after logging in as Admin <IP_OF_SERVER>/updates.  Why is that "processing media..." showing up even on small files?

**Comment by alphabitnz** [comment]
Thanks radiorob. Yes same issue with a 220 KB PNG.

![image](https://user-images.githubusercontent.com/9102111/134698474-6185d93d-b0ab-4792-986d-40820e3c1d1e.png)

I did run all updates & have rebooted the whole machine at least once since then
![image](https://user-images.githubusercontent.com/9102111/134698704-a2a78fdf-6567-4e8a-b68e-f67136979de3.png)
![image](https://user-images.githubusercontent.com/9102111/134698746-bc3b9b5e-d708-4066-877d-a05bc632f96c.png)

**Comment by alphabitnz** [comment]
I am suspecting it might still be a permissions issue, either to some media subfolder or maybe something else I'm not aware of.
If someone can confirm what files/folders need permissions and if ever any user other than www-data that may help find the issue.

**Comment by alphabitnz** [comment]
I've read through the scripted install and manually run the chown/chmod commands used to make sure I have the expected permissions set, but still having the issue so I think it's something else now. Will await advice.

**Comment by alphabitnz** [comment]
Trying to do a fresh install with the script, it seems like it's not calling mysql correctly

```
Next, I would like to know about your MySQL database:

Would you like me to create your database for you (requires you enter your root mysql user/pass): [y]/n
./ob.installer.sh: 47: [[: not found
./ob.installer.sh: 50: [[: not found
./ob.installer.sh: 55: [[: not found

Please enter the name of your OpenBroadcaster Database: [openbroadcaster]

Please provide a user to access the OpenBroadcaster Database: [obdbuser]turnonnz

./ob.installer.sh: 68: read: Illegal option -s

Please enter the MySQL host: [localhost]localhost

If you need a table prefix for your MySQL database, enter it here:


And now, I wish to know how you intend to access your OpenBroadcaster interface:

If you need a prefix for your CSS, enter it here:

Please enter the FQDN of the site's URL: [openbroadcaster.example.com]turnsrv

Please enter the IP of the server hosting openbroadcaster : [192.168.25.10]192.168.1.220

./ob.installer.sh: 83: read: Illegal option -s

./ob.installer.sh: 85: read: Illegal option -s


Now, I am going to ask some things about how to configure your OpenBroadcaster Installation:

Please provide a From email address for OB system mail: [noreply@example.com]turnon@turnon.nz

Please provide a Sender Name for OB system mail: [OpenBroadcaster]Turn On NZ


Thank You.  I will now install OpenBroadcaster...
./ob.installer.sh: 102: [[: not found
./ob.installer.sh: 105: [[: not found
./ob.installer.sh: 108: [[: not found
./ob.installer.sh: 111: [[: not found
./ob.installer.sh: 114: [[: not found
./ob.installer.sh: 117: [[: not found
./ob.installer.sh: 120: [[: not found
./ob.installer.sh: 123: [[: not found
./ob.installer.sh: 126: [[: not found
./ob.installer.sh: 129: [[: not found
./ob.installer.sh: 132: [[: not found
./ob.installer.sh: 135: [[: not found
./ob.installer.sh: 138: [[: not found
./ob.installer.sh: 141: [[: not found
./ob.installer.sh: 162: [[: not found
Enter password:
ERROR 1046 (3D000) at line 29: No database selected
Enter password:
ERROR 1046 (3D000) at line 1: No database selected
```

**Comment by alphabitnz** [comment]
I have now transitioned my install to Mariadb 10.6.4 and still having the same problem

**Comment by bobloblian** [comment]
[[ not found probably means your environment is not set to use the bash shell.  Try calling the script as an argument to bash.  ei:

bash /path/to/script

**Comment by alphabitnz** [comment]
> 
> 
> [[ not found probably means your environment is not set to use the bash shell. Try calling the script as an argument to bash. ie:
> 
> bash /path/to/script

Thanks. That has helped the install script to run without returning any errors, but I still had some issues with its outcome.
I have now dropped any databases I had created for this, wiped out my /var/www/html folder and re-cloned from git to run the script:

$ cd ~/observer/
$ chmod +x ob.installer.sh
$ sudo bash ./ob.installer.sh

I used all default values where possible in the installer, except for 
DocumentRoot = /var/www/html
media files = /mnt/storage/media

$ cd ~/var/www/html
$ sudo php tools/password.change.php admin (redacted password)

so far so good, logged in via web browser, went to /updates/ and hit 'Run Updates Now',
everything green and good on the updates page, uploaded a 55 MB mp4 (avc) and still stuck on 'Processing Media'

So I'm having the same issue after a fresh install using all stated dependencies (substituting libav-tools for ffmpeg) and a clean run of the install script... Linux Mint 20.2

**Comment by radiorob** [comment]
@alphabitnz see new installer [https://github.com/openbroadcaster/observer/blob/main/ob.installer.sh](/observer/main/ob.installer.sh) Good luck!

**Comment by alphabitnz** [comment]
thanks @radiorob ! will let you know how it goes

**Comment by decibecca** [comment]
I'm having the exact problem. Did you finally found the issue with processing media getting stuck?

**Comment by jeffreycarey-aon** [comment]
Rob,
I suspect that the getid3 library that extracts useful information from popular multimedia file formats is broken or invalid.  Can you take a look?
Jeff

**Comment by radiorob** [comment]
need more details to comment, see reporting bugs.  Is this behavior with "Processing Media" present after a fresh install with new installer?
https://github.com/openbroadcaster/observer/blob/main/ob.installer.sh

**Comment by alphabitnz** [comment]
This behaviour was indeed present in testing a fresh install on a fresh ubuntu aws instance even with entdeploy as guided at the time by vincent, though his own already operational environment did not have such an issue even with the exact same file being tested.

Definitely interested to understand why getid3 is the suspected cause, to support further troubleshooting.

**Comment by brookgagnon** [comment]
We should have better debug/error messages in place for this soon. Until then, are you able to check the browser developer tools? Take a look at the network section and see if there is an error there. It would also help to enable PHP error message display (or check logs to find error).

Some possibilities:
- client_max_body_size may need to be increased if using nginx
- post_max_size and upload_max_filesize may need to be increased in php settings
- there might be a missing PHP module
- there might be a permissions issue (error saving uploaded file)

**Comment by alphabitnz** [comment]
Thanks! Created a phptest.php file containing: <?php phpinfo(); ?> and uploaded to the webroot and upload_max_filesize was set to 2M (which I assume is a default the install script doesn't modify).

Tested with a small mp3 file (~500 KB) and the file processed perfectly, so I suppose the lack of error message is the core issue.

Thanks for your help! Will be closing this issue.

**Comment by jeffreycarey-aon** [comment]
> need more details to comment, see reporting bugs. Is this behavior with "Processing Media" present after a fresh install with new installer? https://github.com/openbroadcaster/observer/blob/main/ob.installer.sh

git clone https://github.com/openbroadcaster/observer/blob/main/  ?

## OB Server Installlation Script
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo>
echo "Git Keyring"
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gith>
sudo apt update
sudo apt install gh
echo "Installed gh"

## FFMPEG
cd ~
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

## To Install Default “Main Branch” run:
sudo git clone https://github.com/openbroadcaster/observer.git
#sudo git clone https://github.com/openbroadcaster/observer/blob/main/observer.>
echo "Cloned Main Branch"

# OR

## To Install the optional “Testing Branch” run:
#sudo git clone -b testing https://github.com/openbroadcaster/observer.git
#echo "Cloned Testing Branch"

cd observer
sudo bash ob.installer.sh

ln -s /usr/bin/ffmpeg /usr/local/bin/avconv
ln -s /usr/bin/ffprobe /usr/local/bin/avprobe

**Comment by alphabitnz** [comment]
@jeffreycarey-aon I recommend you try the fixes in my previous post for nginx and php upload limits and timeouts

ID3 tag extraction was working fine after I resolved the issue caused by those settings, if it doesn't fix for you then ideally submit a new issue with as much detail as you can since this one I raised has now been resolved
