### ISSUE TITLE
Latest 5.11 - Observer webpage completely blank after update

### ISSUE THREAD

**Issue by alphabitnz** [openbroadcaster/observer#21]
Built-in ./updates/ webpage tool did not show any updates, so I copied files to webroot and set permissions.

That didn't work so I purged the webroot directory, the ~/.openbroadcaster directory, dropped the mysql schema and ran the ob.installer.sh script for a fresh install.

Web access still showed totally blank page, so I suspected a conflict due to installer forcing install of php7.0 dependency when I had preferred to more recent php packages - eg php8.0-mysql or the meta packages e.g. php-mysql.
Proceeded to purge php* and install packages fresh, but that didn't fix the issue so I purged all dependencies and files including apache2* and re-ran the built in script.

Still just getting a completely blank landing page. Can still browse to non-php assets like /favicon.ico or /install.txt fine but it seems like any php files are not processing correctly.

Currently installed php version is showing as 7.0 as per dependencies
> $ php -v
> PHP 7.0.33-55+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Oct 22 2021 12:34:57) ( NTS )

**Comment by radiorob** [comment]
Thank you very much @alphabitnz for testing this quickly.  Forgot some files and have updated release.

**Comment by alphabitnz** [comment]
> 
> 
> Thank you very much @alphabitnz for testing this quickly. Forgot some files and have updated release.

Hi Rob
@radiorob 

Still not working after cloning from git right now and replacing the webroot directory with new files, and I notice the assets directory is completely missing from the current release.

Can you please confirm when the fixed new release is available, and also what the expected method of upgrading is as it doesn't look like the web-based upgrade utility is the right thing, and straight up replacing the webroot directory will likely need additional steps such as chmod/chown. And I don't like the installer script as I have mentioned it force installs the php7.0 dependencies when I prefer to run php8.0.

**Comment by radiorob** [comment]
Please disregard installer for now, it is getting a major rework for 5.1.1 (but wasn't able to get it included), but please include anything that it should do/preferences.  @brookgagnon can advise what this issue is. Thanks again.

**Comment by alphabitnz** [comment]
> 
> 
> Please disregard installer for now, it is getting a major rework for 5.1.1 (but wasn't able to get it included), but please include anything that it should do/preferences. @brookgagnon can advise what this issue is. Thanks again.

Noted, thanks very much Rob.

Awaiting 
1. confirmation how I should be pulling the new release once it is confirmed working
2. instructions on upgrade methodology e.g. 
   1. backup old config.php
   2. copy release directory to webroot
   3. insert backed up config.php
   4. required chmod/chown operations
   5. anything else...

I'm happy to assist with the new installer wherever possible, including code for your consideration.

**Comment by radiorob** [comment]
Getting this same behavior on our demo environments after an update. Login works OK on ENG. Blank screen on login for all other languages.

**Comment by radiorob** [comment]
*** After install, set OB_UPDATES_USER and OB_UPDATES_PW in config.php and then run https://YOUR_IP/updates ***

Administrator login is no longer supported for OB updates since July 2020.
