### ISSUE TITLE
Tracks doubling up after saving in playlist.

### ISSUE THREAD

**Issue by billpolonsky** [openbroadcaster/observer#24]
**Describe the bug**
tracks in playlist double up  in playlist after saving. Often after reopening playlist.

**To Reproduce**
Random happening.
Has happened at least 4 times to me in the past month.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Mac os with CHROME

**Additional context**
.
![double-screenshots](https://user-images.githubusercontent.com/4603894/142705792-0c9cc267-f19d-4d22-a1ef-246393829870.png)

**Comment by radiorob** [comment]
Couldn't replicate but saw your PL doubling up with my profile.  Did you try delete the dups, saving.  Does it get doubled up automatically?  On radio heard CJUC PL doubling up Station Ids

**Comment by radiorob** [comment]
haven't seen this error message before.  Doesn't like that PL
![Screenshot at 2021-11-17 14-45-19](https://user-images.githubusercontent.com/4603894/142748622-5e2cfc5e-364d-4bb6-a5db-ebfedb02b134.png)

**Comment by radiorob** [comment]
Server isn't set up to handle two identical requests back to back

Create a new playlist, click save once
Edit that playlist.  double click the save button twice in quick succession
exit the playlist and reopen it, it will have duplicate tracks
![image](https://github.com/openbroadcaster/observer/assets/4603894/7df83be2-3629-41c6-8b68-ff790cbd548d)

**Comment by radiorob** [comment]
I managed to duplicate a whole playlist by double clicking the save button also .. that's not supposed to happen either
Double clicking twice - so quad clicking basically

**Comment by radiorob** [comment]
Tweaks to server code fixed this.  Thanks cjucfm.com
