### ISSUE TITLE
Upload of Multiple Files - id3 Tags of Cancelled File Used on Next

### ISSUE THREAD

**Issue by ScriptsByChris** [openbroadcaster/observer#3]
I uploaded a batch of files and some failed to upload. I cancelled the failed files but the id3 tags were used on the next file in the list.

Feature Request: Watch Folder(s) with default actions/parameters

**Comment by radiorob** [comment]
Newest Dev server code revamps the uploader and junk filter.  Checks file format first, then allows updating ID3 info.

**Comment by radiorob** [comment]
added to wishlist on forums https://openbroadcaster.com/content/watch-folders
