### ISSUE TITLE
Upload stops at 16MB

### ISSUE THREAD

**Issue by jeffreycarey-aon** [openbroadcaster/observer#36]
I am attempting to up load media but one of two things happen:

1. If the file is greater than 16 MB it stops uploading OR:
2. If the file is < than 16 MB it processes indeterminately. 

Any Ideas?

**Comment by radiorob** [comment]
bandwidth issues?
https://github.com/openbroadcaster/observer/blob/main/ob.installer.sh

**Comment by alphabitnz** [comment]
see if my resolution notes from #17 might help here
