### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lamousis** [openbroadcaster/observer#37]
I' ve been trying to install openbradcaster server to a remote web server and i keep getting the error message 

OB_SITE (installation web address) does not appear to point to a valid OpenBroadcaster installation.

In config.php in const OB_SITE i have entered "localhost", then the server's hostname, the its ip address but the error is still there
I used a manual installation creating the database, and the users. The system the server has is ubuntu 16.04
Am i doing something wrong?
Can you please post more detail instructions about the server installation??

**Comment by brookgagnon** [comment]
Sorry for the long wait for a reply on this issue. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
