### ISSUE TITLE
Cant upload audio, with response This file format is not supported.

### ISSUE THREAD

**Issue by ramcona** [openbroadcaster/observer#40]
**Describe the bug**
i was follow on dependency.txt with use 
ln -s /usr/bin/ffprobe /usr/local/bin/avprobe and
ln -s /usr/bin/ffmpeg /usr/local/bin/avconv

and on media setting i was check all media file format but when after done upload audio .mp3, cant to save with message "This file format is not supported". 

i use  Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-89-generic x86_64)

**Comment by tommyz4** [comment]
Getting the same error? any fix

**Comment by tommyz4** [comment]
@ramcona  I figured it out. If you have ffmepg installed use


** If libav-tools package is not available, install ffmpeg package instead, and symlink the following:

ln -s /usr/bin/ffmpeg /usr/local/bin/avconv
ln -s /usr/bin/ffprobe /usr/local/bin/avprobe

**Comment by ramcona** [comment]
yes sir, i was run the command and have already symbolic link

**Comment by brookgagnon** [comment]
Sorry for the long wait for a reply on this issue. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
