### ISSUE TITLE
libavfilter-extra (unable to find package - 16.04)

### ISSUE THREAD

**Issue by d3ssen** [openbroadcaster/observer#5]
Trying to install observer dependencies shows that "libavfilter-extra" can't be found.
It's part of the ffmpeg 7 package which is already installed.

Can observer run without libavfilter-extra? (libavfilter-ffmpeg5 is installed)
Or can I install the dependency via another route?

**Comment by coryshort** [comment]
you could try to use this `https://packages.debian.org/sid/all/libavfilter-extra/download`. Sorry i cant help more right now
