### ISSUE TITLE
Switch to ISO language list/codes for language metadata

### ISSUE THREAD

**Issue by alphabitnz** [openbroadcaster/observer#66]
Please add 'Te Reo Māori' as an option for Language field in Core Metadata
Thanks in advance.

For more information about Te Reo please see:
https://www.tpk.govt.nz/en/whakamahia/te-reo-maori

**Comment by brookgagnon** [comment]
Feature - planned switch to iso language codes.

**Comment by radiorob** [comment]
Fixed in [release v5.3.2](https://github.com/openbroadcaster/observer/releases/tag/v5.3.2)
