### ISSUE TITLE
Admin Login is not possible

### ISSUE THREAD

**Issue by ProTechEx** [openbroadcaster/observer#71]
I have install OpenBroadcaster on VPS. Installation was succesfull.

I can't login as admin.
User: admin
Pass: mypass

When i try to login, i don't get a "incorrect" error message.  After entering the correct credentials and hot the login button, username and password text fields are emptied again and it does nothing.

I also change in the config.php
const OB_SITE = 'http://mydyndns.com';

I also try to change my password with 
`php tools/password_change.php admin mypass`

but still the same. How to fix this issue ?

**Comment by Xenarc** [comment]
Thanks for raising this issue! In future, it may be more helpful to provide additional logging output from php.

However, can I confirm that you have run the 'Updates' script? This occassionally pops up when updates havn't been run, or if there's an error conencting to the database service. This is accessible from [http://mydyndns.com/updates/](http://mydyndns.com/updates/). 

If this isn't the issue, you will -- as noted -- need to provide the server logs.

**Comment by tsyuha** [comment]
> I have install OpenBroadcaster on VPS. Installation was succesfull.
> 
> I can't login as admin. User: admin Pass: mypass
> 
> When i try to login, i don't get a "incorrect" error message. After entering the correct credentials and hot the login button, username and password text fields are emptied again and it does nothing.
> 
> I also change in the config.php const OB_SITE = 'http://mydyndns.com';
> 
> I also try to change my password with `php tools/password_change.php admin mypass`
> 
> but still the same. How to fix this issue ?

all the same. please help

**Comment by tsyuha** [comment]
> Thanks for raising this issue! In future, it may be more helpful to provide additional logging output from php.
> 
> However, can I confirm that you have run the 'Updates' script? This occassionally pops up when updates havn't been run, or if there's an error conencting to the database service. This is accessible from http://mydyndns.com/updates/.
> 
> If this isn't the issue, you will -- as noted -- need to provide the server logs.

you write about launching updates, but as I understand it, they need to be launched after authorization, and I and topikstarter just can't go to the admin panel and can't be authorized.
server error logs are empty

**Comment by Xenarc** [comment]
Hi @tsyuha, as per the [installation instructions](https://github.com/openbroadcaster/observer/blob/main/install.txt), the last installation step (8) is to run the updates script. Please let us know if that is successful. Cheers ~MB

**Comment by tsyuha** [comment]
Thank you for answer but 

here is the 8th step -
Log into OpenBroadcaster as admin, and access http://ob_install_url/updates/ to
   verify your installation and run any required updates.

I can't log into OpenBroadcaster as admin - this is a main problem. Update have to be after log into. I can't log into)))

**Comment by tsyuha** [comment]
I understood all. Thank you very much!!

**Comment by brookgagnon** [comment]
Sorry for the long wait for a reply on this issue. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
