### ISSUE TITLE
Not Working on my ubuntu vps

### ISSUE THREAD

**Issue by sankamaduranga** [openbroadcaster/observer#76]
only show login page

   sudo apt update and upgrade
   sudo apt install git
  sudo adduser obsuser
  sudo usermod obsuser -a -G pi,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,spi,i2c,gpio
  mkdir gits && cd gits
  sudo git clone https://github.com/openbroadcaster/observer.git
  cd observer && sudo bash ob.installer.sh
 ln -s /usr/bin/ffmpeg /usr/local/bin/avconv
 ln -s /usr/bin/ffprobe /usr/local/bin/avprobe
 Navigate to http://(SERVER_IP)/updates/ and login with: updates/updates

**Comment by brookgagnon** [comment]
Sorry for the long wait for a reply on this issue. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
