### ISSUE TITLE
"The file format is not supported" but with logs

### ISSUE THREAD

**Issue by STDEin** [openbroadcaster/observer#77]
**Describe the bug**
Uploading media EXCEPT images returns "The file format is not supported"

**To Reproduce**
From fresh install of observer on Ubuntu 22.04, php7.4-fpm, ffmpeg and other dependencies
avconv replaced with link to ffmpeg
`ln -s /usr/bin/ffmpeg /usr/local/bin/avconv`
`ln -s /usr/bin/ffplay /usr/local/bin/avprobe`
post_max_size in php.ini, and client_max_body_size and the timeouts in nginx.conf adjusted

Uploading any media other than images (h264+aac in mp4 of various sizes and source, mp3, and flac audio tested) from the web interface returns
`This file format is not supported.`

/var/log/nginx/error.log contains one entry per attempted upload
`2022/08/09 23:56:44 [error] 1095#1095: *92 FastCGI sent in stderr: "PHP message: PHP Notice:  Missing argument: type in /var/www/observer/classes/obfhelpers.php on line 82PHP message: PHP Notice:  Missing argument: format in /var/www/observer/classes/obfhelpers.php on line 82" while reading response header from upstream, client: 192.168.100.125, server: _, request: "POST /upload.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "192.168.100.71", referrer: "http://192.168.100.71/"
`

**Expected behavior**
Upload processes and is passed to the transcode service

**Server**
 - OS: Ubuntu 22.04 (updated to current as of 2022-08-09)
 - php7.4-fpm installed from ppa:ondrej/php

**Desktop**
 - Windows 10 21H1
 - Browser Chrome 103.0.5060.134

**Comment by brookgagnon** [comment]
Sorry for the long wait for a reply on this issue. If you're still working on this, could you let me know your [Discord](https://discord.com/) username so we can work together to resolve this issue (and fix any associated bugs if applicable)? Or send me a message on Discord - nightwolf#5044
