### ISSUE TITLE
no logins work new install

### ISSUE THREAD

**Issue by SpudGunMan** [openbroadcaster/observer#81]
**Describe the bug**
new install with installer.sh script

**To Reproduce**
newos,git clone, run installer.sh
cant login with set password or attempted reset of admin admin, no login accepted.
updates account won't login

if wrong password used that error shows up but the login just dies

**Expected behavior**
script login/password combo to work

**Desktop (please complete the following information):**
 - OS: debian/Pi64 replicated on a fresh mint install X86 as well.
 - Browser chrome
 - Version git pull:main

**Comment by brookgagnon** [comment]
We have been having some issues with this install script. We're working on it. You may wish to consider this install script instead:
https://github.com/brookgagnon/ob-install/ (requires fresh Ubuntu 20.04 install).

**Comment by SpudGunMan** [comment]
that script was no good either (using 20.04 focal vm)

**Comment by brookgagnon** [comment]
Okay, script is half baked still :). Works when it works but ya.

Can you either: 

1. Fresh Ubuntu 20.04 install, run the script again and log all the output / attach to comment here? Or,
2. Meet us on Discord so we can debug together? (Let me know your discord username).

thanks!

**Comment by brookgagnon** [comment]
> yes I can, username is same as this SpudGunMan I didn't see a discord group first search?

Currently a private server as it's new (plans to make public later). There should be 4 digits after your username, could you confirm those? Thanks!

**Comment by SpudGunMan** [comment]
I just noticed OBplayer also still uses python2? this might be more effort to forklift for my use case I am going to likely head a different direction.

**Comment by radiorob** [comment]
> I just noticed OBplayer also still uses python2? this might be more effort to forklift for my use case I am going to likely head a different direction.

Already supports Python 3  See [change Log](https://openbroadcaster.com/resource/change-log/)

**Comment by SpudGunMan** [comment]
> > I just noticed OBplayer also still uses python2? this might be more effort to forklift for my use case I am going to likely head a different direction.
> 
> 
> 
> Already supports Python 3  See [change Log](https://openbroadcaster.com/resource/change-log/)

Good to know I loaded the script as published and it required python2 

Might be good to update that?

**Comment by radiorob** [comment]
Thanks.  Where did you see it asking for python2?  Was this in the observer installer?  Obplayer doesn't come with an installer.

**Comment by SpudGunMan** [comment]
Could be the problem the instructions said to run 


https://github.com/openbroadcaster/obplayer/blob/main/obplayer_check

Which pulls via python2 I will look to load just directly. Was following too closely I suppose! Sorry
