### ISSUE TITLE
Silence Detection on Corrupted Media

### ISSUE THREAD

**Issue by radiorob** [openbroadcaster/observer#82]
Assuming all is working properly with scheduling and playout, there are sometimes gaps and dead air. These instances are few and far between and when we do get silence, we dig into the cause.   When initially uploading media, we do some basic crc checking and junk filtering to keep out bad media.     Sometimes media gets in that causes silence playout issues.

Solution

1) In >Media Settings, disable all compressed formats and only allow users to upload material in /Ogg/OPUS/Wav/FLAC  We can do this now.

2) When uploading, do an additional acoustic check on media to look for erroneous blank spots 

3) A CLI tool that can be run on a large media library to check for silence gaps and flag other corrupted conditions not caught in upload tool

Examples of badly encoded media that has silence in the middle or end of recording
 
![Silence detection inside media items](https://user-images.githubusercontent.com/4603894/203842908-3c5693de-ecdb-4929-a8ec-37e84f7ce692.png)
Silence detection inside media items
![gap-in-recording](https://user-images.githubusercontent.com/4603894/203842912-0b634496-d17c-4362-b6d1-6376298acdd1.jpg)
gap-in-recording
![silence at end of recording](https://user-images.githubusercontent.com/4603894/203842915-a2e9d195-bae2-48b1-85de-5ef717fc8370.png)
silence at end of recording
![crc check failed](https://user-images.githubusercontent.com/4603894/203842922-c15a97e7-9f40-4336-b96e-d0ff9187fc4b.png)
crc check failed

**Comment by ltyndale** [comment]
To be honest, this seems more like a production issue then a problem that the automation system should be worried about.  People should not be uploading poor audio.  When audio is added to the system it should first be checked to make sure it is good, with proper normalized levels (unlike example 1 and 2 above, where they not only have large silent spots, but it appears that the audio after the silent spot is not normalized to the same level as the audio before the silent spot), no bad spots, properly mixed down to mono in the case of an AM or mono station, its left and right tracks in phase (as opposed to being out of phase and causing silence on the air), and anything else that needs to be done.  All of this is part of producing good audio.  Once their audio is properly checked for all of this and normalized to whatever normalization standard is set for the station, then ideally an uncompressed BWF (Broadcast Wave Format) file should be what gets uploaded (and preferably checked once the upload is done before it goes to air).

**Comment by radiorob** [comment]
Correct.  Garbage in garbage out.  OBVer1, terrible uptime, nonstop troubleshooting until we dumped all the corrupted mp3 and only used Ogg.  That made a huge difference. +1 for best practices at station.  Real world, some users (me) are just plain lazy\busy to check levels, include all metadata or even have an understanding of the codec (esp Video) are using in a rush to get material on air.  First thing I try when evaluating a radio system is to rename a *.doc fileto *.mp3 and then see if I can upload and ingest into media library.  Now we are looking at a future where there is no production, just hit record on cellphone, upload and hope for the best.

**Comment by radiorob** [comment]
updated above, right now in new installs, for best practice admins can disable all formats except uncompressed audio.  So this is a tool needed for maintenance of large libraries to do this type of check.  The CJUC library has over 130K media items, some from old days, early 2000's sound awful mp3@64kb  With decent internet these days, no need to be sending around compressed files in an automation system.

**Comment by radiorob** [comment]
adding support for BWF archival purposes
https://github.com/openbroadcaster/observer/issues/166
